// app/layout.tsx
import type { Metadata } from "next";
import { Archivo_Black, Lexend_Mega } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import { SessionProvider } from "next-auth/react";

const archivoBlack = Archivo_Black({
  variable: "--font-archivo-black",
  subsets: ["latin"],
  weight: ["400"], // Archivo Black n'a qu'un seul poids dispo
});

const lexendMega = Lexend_Mega({
  variable: "--font-lexend-mega",
  subsets: ["latin"],
  weight: ["400"], // Lexend Mega aussi
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivoBlack.variable} ${lexendMega.variable} antialiased`}
      >
        <SessionProvider>
          <div className="mx-auto w-72 sm:w-96 md:w-[600px] lg:w-[800px] xl:w-full max-w-6xl">
            <Header />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
